services:
  autorotate:
    build: .
    container_name: autorotate
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
      - cs2-network
networks:
  proxy:
    external: true
  cs2-network:
    external: true
